- docs/src/Main.elm
- docs/src/Texts.elm
- src/UI/RenderConfig.elm
- src/UI/Text.elm
- tests/Tests/UI/RenderConfig.elm
Requires #2 
What this PR does?:
* Add a property to AppConfig that dictates global details about rendering components.
* It can be used to determine responsive constraints at runtime.
* In the future, it can be used for things like dynamic dark-mode.
Missing:
* Obtain real window's width and height in paack-ui's docs!
* Documents on how to initialize and use.
> WMS-136 | Add RenderConfig (Global runtime settings for all components)

- src/UI/Button.elm
Centralize text when the button is in full-width mode
> Fix full width button

- src/UI/Internal/Dialog.elm
- src/UI/NavigationContainer.elm
- src/UI/Utils/ARIA.elm
- src/UI/Utils/Element.elm
Left over from previous discussions:
* No laziness in NavigationContainer
* Screen readers don't go into SVG images, following this doc: https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Role_Img
> Enhancements 2020-05-19

- src/UI/Icon.elm
This allows non-sense sizes like the one giant warning on the WMS.PackageStatusLookup screen
> [UI] Add withCustomSize

- src/UI/Internal/Text.elm
- src/UI/Internal/Utils/Element.elm
- src/UI/Utils/Element.elm
So apparently, the ellipsis feature was not working properly, I'm not sure if ever did taking into account this issue opened: [Click here](https://github.com/mdgriffith/elm-ui/issues/49).
Before: 
After
It's quite hackish, but blame elm-ui :o
> WMS-399 | Fix ellipsis behaviour

- showcase/src/Tables/Stories.elm
- src/UI/Internal/Tables/Common.elm
- src/UI/Internal/Tables/View.elm
- src/UI/Tables/Common.elm
Previously we could only render a button or text in table cells, this change will allow rendering any custom element.
[WMS-416](https://paacklogistics.atlassian.net/browse/WMS-416) needs to render a badge inside a cell, and waiting on this change to get merged.
[WMS-438](https://paacklogistics.atlassian.net/browse/WMS-438)
None
> WMS-438 | Allow custom element table cells

- cypress/integration/visual-regression.spec.js
- package.json
- showcase/src/Tables/Book.elm
- showcase/src/Tables/Stories.elm
- src/UI/Internal/Tables/View.elm
Fixing the issue where the portion columns were overflowing
Adding an example to cover this use case
[WMS-473](https://paacklogistics.atlassian.net/browse/WMS-473)
> Add min width to portion cells and examples

- src/UI/Internal/Text.elm
Remove a clipX that was misplaced.
> Packages table is not being displayed in the spaces page (Mobile view)
(Nobre, Jouderian F.)
[https://paacklogistics.atlassian.net/browse/WMS-508](WMS-508)
None
This is my grand finale per today!
> WMS-508 | Fix Package-page's Table on Mobile

- src/UI/Internal/Tables/View.elm
- src/UI/Internal/Text.elm
- src/UI/Internal/ToggleableList.elm
- src/UI/Internal/Utils/Element.elm
- src/UI/Text.elm
- src/UI/TextField.elm
Replace `setEllipsis` function with a new `withOverflow` function
Because we need to stop defaulting to the tooltip behavior for every case
[WMS-519](https://paacklogistics.atlassian.net/browse/WMS-519)
> Replace setEllipsis with withOverflow

- src/UI/Checkbox.elm
- src/UI/Internal/Tables/FiltersView.elm
- src/UI/Internal/Utils/Element.elm
- src/UI/Radio.elm
- src/UI/Tables/Stateful.elm
Makes table filters dialog to fit its contents, also sets the dimensions for radio buttons and checkboxes as per [feedback by Sufyan](https://www.figma.com/file/rqAoj2WwQZYoisP2G6d6nJ?node-id=1:41#37303481). I am making checboxes dimension changes part of this PR because they were contributing to the dialog overflow.
Since contents of table filter were overflowing its boundary sometimes, have a look at [this PR](https://github.com/PaackEng/wms-web/pull/114) for context.
[WMS-518](https://paacklogistics.atlassian.net/browse/WMS-518)
Now a filter dialog will be sometimes of lesser width than the column width. I tried setting a minimum width (equal to the column width) on the dialog but couldn't make it work because there is no function exposed by Elm-UI to convert `Element.Length` to …
> WMS-518 | Fix filter dialog overflow and set dimensions for checkboxes and radio buttons

- src/UI/Internal/Tables/FiltersView.elm
* Normalize all icons to the same size
* Remove extra padding in icons.
Based on this node https://www.figma.com/file/DTyoSveNksHpZCdU8a7BNs/Dashboard?node-id=89%3A831
Because at some point these glitches were merged
None, just a hotfix.
Based on master and not blocked.
Nothing
We need to deploy to live demo at some point.
> Fix different header size from Figma

- src/UI/Internal/Tables/FiltersView.elm
Like the previous PR, plus the "row selection's column's header". Added a warning and replaced other `Sizes.extraSmall` I found giving soup!
Cause we're all humans!
None, just a small fix.
Not blocked and based on master.
Nothing
I like all flavors of ice cream equally!
> Fix different header size from Figma ++

- package.json
- src/UI/Internal/Text.elm
- yarn.lock
Makes `ellipsizable-text` use the new API resulting from [this PR](https://github.com/PaackEng/paack-ui-assets/pull/8).
[This PR](https://github.com/PaackEng/paack-ui-assets/pull/8) has some details.
[WMS-529](https://paacklogistics.atlassian.net/browse/WMS-529)
[#8](https://github.com/PaackEng/paack-ui-assets/pull/8)
> WMS-529 | Make ellipsizable-text conform to new api

- src/UI/Badge.elm
Switch the dark warning/danger badge colors
Because they were wrong, basically
[WMS-553](https://paacklogistics.atlassian.net/browse/WMS-553)
> WMS-553 | Fix badge warning/danger colors

- src/UI/TextField.elm
- src/UI/Utils/Element.elm
* Adds `name="username"` to username fields.
> Right now, we LastPass is not working properly in our login page, it seems that the autocomplete is not working. It’s nice to have it working, Xavier mentioned that we just need to wrap the textfields with a <form> but I think it will be nice to take a look in the last pass documentation and see the best way to approach this.
[WMS-598](https://paacklogistics.atlassian.net/browse/WMS-589)
Nothing.
After merging, requires bump in WMS.
> WMS-589 | Make our login page comply to LastPass

- src/UI/Button.elm
- src/UI/Internal/Button.elm
- src/UI/Internal/Nav/StackHeader.elm
- src/UI/Internal/NavigationContainer.elm
- src/UI/Internal/SideBar.elm
- src/UI/Layout/SplitSelectable.elm
- src/UI/ListView.elm
- src/UI/NavigationContainer.elm
Fix inconsistencies between Figma's mobile spaces and current implementation:
* Defines the button's style in the mobile's header;
* Allow customizing the mobile's stacked header's title;
* Update mobile's header's sandwich size and color;
* Center mobile's stacked header title;
* Force mobile's stacked header elliptization;
* Update SelectList's action bar padding.
Cause it differed from Figma.
[WMS-587](https://paacklogistics.atlassian.net/browse/WMS-587)
**Comments in Figma**
Nothing
This JIRA card was smaller, but those changes are all in the same Figma screen/component.
> WMS-587 | Fix inconsistencies between Figma's mobile spaces and current implementation

- .editorconfig
- .github/workflows/ci.yml
* Adopt the same CI conditions as WMS:
* Skip draft PRs,
* Run actions in PRs only once,
* Run CI on master when merges and tags;
* Stop messing Elm indentation through `.editorconfig`.
Small enhancements.
Not tracked.
Not blocked.
Nothing.
> Adopt the same CI conditions as WMS; Stop messing Elm indentation

- src/UI/Internal/SideBar.elm
Center and fix padding to the collapsed sidebar button
> The menu logo its not aligned when the menu it's in slim mode
[WMS-633](https://paacklogistics.atlassian.net/browse/WMS-633)
> WMS-633 | Center and fix padding to the collpased sidebar button

- showcase/src/Tables/Book.elm
- src/UI/Internal/Tables/View.elm
- src/UI/Tables/Common.elm
- src/UI/Tables/Stateful.elm
- src/UI/Tables/Stateless.elm
This PR is open for discussions as well!
Uses `Element.Keyed` in `UI.Table`, enhancing diffing.
I've made it as a POC, it ended up being easier then it looked like.
As we don't have that many rows, it may not bring any benefit.
None, mostly a POC.
#89
In other PR:
- Do the same to `UI.ListView`
- Do the same to `UI.NavigationContainer`
I watched more animes in 2020 than the rest of my entire life.
>  Use Keyed elements in Table

- src/UI/Internal/Tables/View.elm
Share the same attributes for text and links.
The padding was different.
Related to WMS-726.
Nothing.
> Fix incompatible paddings between text and links in Tables

- .github/workflows/percy.yml
- package.json
- Keep Elm' debugger out of Percy's screenshots.
- It was meddling with reviewing.
Not tracked.
Not blocked.
- To discover if it works!
> Disable elm-debugging in Percy

- cypress/integration/visual-regression.spec.js
- elm.json
- showcase/src/Dialog.elm
- showcase/src/Main.elm
- src/UI/Internal/DialogV2.elm
- src/UI/NavigationContainer.elm
- src/UI/V2/Dialog.elm
Adds another Dialog component as discussed in this [RFC](https://paacklogistics.atlassian.net/wiki/spaces/EN/pages/2089025545/New+Dialog+API),
Check out the RFC
[WMS-715](https://paacklogistics.atlassian.net/browse/WMS-715)
I have made icon in the title as mandatory to create this version of the dialog and removed close message as an argument since this version of the dialog is not going to have a cross button to close the dialog nor it will have the overlay. Have a look at [this conversation](https://www.figma.com/file/DTyoSveNksHpZCdU8a7BNs?node-id=369:29#50879134) regarding the title in the icon and removal of the cross button.
> WMS-715 | Add v2 of dialog as a POC

- elm.json
- src/UI/Internal/DialogV2.elm
- src/UI/NavigationContainer.elm
- src/UI/V2/Dialog.elm
Remove exposed module `UI.V2.Dialog` from elm.json and fix elm-analyse issues
Since it was causing elm-analyse to crash due to [this bug](https://github.com/stil4m/elm-analyse/issues/198).
> Remve UI.V2.Dialog from elm.json causing elm-analyse to fail

- .github/dependabot.yml
* Disables auto-rebasing for dependabot's PRs
* It's wasting CI and GH Actions resources;
* It's delaying higher-priority rebases.
Not tracked
Not blocked.
Nothing
> Disables auto-rebasing for dependabot's PRs

- src/UI/Utils/Element.elm
Add the `renderIf` utility 
Because it's needed in multiple projects already
> Add renderIf utility

- .github/workflows/percy.yml
* Do not run Percy when PR is a draft
* Drafts are mostly POC and we don't want to waste our free screenshots, changing it to non-draft reenables Percy and other CIs, and that is required before merging...
Not tracked.
Not blocked.
Nothing at all.
> Do not run Percy when PR is a draft

- elm.json
- src/UI/SummaryListItem.elm
Add UI.SummaryListItem to the exposed modules and document it
Because it's used everywhere but we forgot to expose it :sweat_smile:
> Expose summary list item

- elm.json
- showcase/src/Sidebar/Stories.elm
- src/UI/Internal/Menu.elm
- src/UI/NavigationContainer.elm
- src/UI/Utils/Element.elm
Smol hack to force the sidebar to start closed when non-persistent
Fix the sidebar overlay that was preventing clicks on the content
Because these are the two issues I found testing the sidebar in a real app with the `NavigationContainer`
> Sidebar Hotfix

- .github/workflows/ci.yml
- package.json
- showcase/elm.json
- src/UI/Icon.elm
- yarn.lock
* Change working-directory and directories for elm-review in CI;
* Bump `yarn.lock` (closes #169);
* Change working-directory and directories for elm-review in `packages.json`;
* Applies changes suggested by elm-review.
* It was broken and we didn't notice until I added `NoUsed.Modules.rules`
Not tracked.
Not blocked.
> Fix and apply elm-review

- .editorconfig
- i18n/English.json
- i18n/French.json
- i18n/Spanish.json
- package.json
- showcase/src/Tables/Book.elm
- showcase/src/Tables/Model.elm
- showcase/src/Tables/Stories.elm
- src/I18n/English.elm
- src/I18n/French.elm
- src/I18n/Spanish.elm
- src/I18n/Types.elm
- src/UI/Icon.elm
- src/UI/Internal/Basics.elm
- src/UI/Internal/Tables/Filters.elm
- src/UI/Internal/Tables/FiltersView.elm
- src/UI/Internal/Tables/Sorters.elm
- src/UI/Internal/Utils/Element.elm
- src/UI/Tables/Stateful.elm
- yarn.lock
* Allows `Tables.Stateful` to have per-column sorting;
* Add `stateWithItems` and `stateWithSorters`, while caching filtered+sorted items in state;
* Update translations;
* Update paack-ui-assets (Including Icons);
* Add config so editors will keep POEditor formatting in i18n's JSONs.
> As column headers are common UI elements this change have an impact on DS. Let’s propose a header component that allows different actions to modify the table, like order and filter. -- Marchese, Juan
[WMS-652](https://paacklogistics.atlassian.net/browse/WMS-652) and [DES-29](https://paacklogistics.atlassian.net/browse/DES-29)
Not blocked anymore.
> DES-29 ⊕ WMS-652 | Table sort

- showcase/src/Tables/Stories.elm
- src/UI/Effect.elm
- src/UI/Internal/Tables/Filters.elm
- src/UI/Internal/Tables/Sorters.elm
- src/UI/Tables/Stateful.elm
Replace `Cmd` with `Effect` in `Stateful` table.
- Support to `elm-program-test`.
- Possible to intercept these effects in tests from other applications like `wms-web`.
This is a prequel to adding analytics support to `paack-ui` (analytics events are planned to be an effect tag).
To keep things simple, the `Effect` type here is not a list yet, but it may turn into one someday if required.
> Port Stateful table from Cmd to Effects

- src/UI/Analytics.elm
- src/UI/Effect.elm
- src/UI/Internal/Analytics.elm
- src/UI/Internal/Tables/Filters.elm
- src/UI/Internal/Tables/Sorters.elm
- src/UI/Tables/Stateful.elm
1. Add some `Analytics` events for table filters and sorters
2.  `Effect` is now a `List (SideEffect msg)` like on `wms-web`
1. To provide more analytics events to `wms-web`
2. Because the previous change required firing `Analytics` along with a `MsgToCmd` effect
[WMS-794](https://paacklogistics.atlassian.net/browse/WMS-794)
> WMS-794 | Table Analytics

- cypress/integration/visual-regression.spec.js
- elm.json
- i18n/English.json
- i18n/French.json
- i18n/Spanish.json
- package.json
- showcase/src/ContentPlaceholders.elm
- showcase/src/Main.elm
- showcase/src/Tables/Stories.elm
- showcase/src/Utils.elm
- src/I18n/English.elm
- src/I18n/French.elm
- src/I18n/Spanish.elm
- src/I18n/Types.elm
- src/UI/ContentPlaceholder.elm
- src/UI/Icon.elm
- src/UI/SummaryListItem.elm
- yarn.lock
Implements this baby: https://www.figma.com/file/piyT6sDqja7yG7QarvmAZ9/Empty-States
* Good guy Sufyian noticed this pattern repeating a lot between screens and decided to upgrade it to a component.
* We're using this [in WMS Phase 4](https://www.figma.com/file/DTyoSveNksHpZCdU8a7BNs/Dashboard?node-id=1855%3A26417)
[WMS-801](https://paacklogistics.atlassian.net/browse/WMS-801)
* ~I need to add that "Fix" icon into paack-ui-assets.~ SOLVED
> WMS-801 | Add "empty states" component

- src/UI/Internal/Tables/FiltersView.elm
- src/UI/Tables/Stateful.elm
* Auto close headers' dialog after sorting;
* Add minimum width to headers' dialogs;
This was the desired behavior and was accidentally dropped when adding effects.
[WMS-812](https://paacklogistics.atlassian.net/browse/WMS-812)
Not blocked.
Nothing pending.
> WMS-812 | Fix table sorting behaviour to deploy it

- elm.json
- src/UI/Internal/Analytics.elm
When sorting tables' columns:
* Instead of `reverse=true`, register it as `direction=descending`;
* Instead of `reverse=false`, register it as `direction=ascending`;
* It was confusing to see it as it's in Mixpanel.
Not tracked.
Not blocked.
Nothing.
> WMS-812 | Sort direction instead of reverse

- .github/workflows/ci.yml
- elm.json
- showcase/src/Layouts/Stories.elm
- showcase/src/Radio/Stories.elm
- src/UI/Button.elm
- src/UI/Internal/Button.elm
- src/UI/Internal/Dialog.elm
- src/UI/Internal/DialogV2.elm
- src/UI/Internal/Nav/StackHeader.elm
- src/UI/Internal/Text.elm
- src/UI/ListView.elm
- src/UI/ListView/SummaryItem.elm
- src/UI/NavigationContainer.elm
- src/UI/Radio.elm
- src/UI/Tabs.elm
- src/UI/V2/Dialog.elm
- src/UI/V2/SummaryListItem.elm
- Add `UI.ListView.SummaryItem`:
- roughly the same as `UI.SummaryListItem` but using "with pattern"
- optional badge using `withBadge`
- optional checkbox using `withCheckbox`
- consistent with [Figma](https://www.figma.com/file/DTyoSveNksHpZCdU8a7BNs/Dashboard?node-id=1813%3A96)
- Add `UI.ListView.simpleList`:
- basically the same as `UI.ListView.selectList` but without built-in selection
- no visual changes
- Update `Layouts.Stories` to use `UI.ListView.SummaryItem`
- When not using checkbox:
- When using checkbox and removing selection's background:
- [Figma](https://www.figma.com/file/DTyoSveNksHpZCdU8a7BNs/Dashboard?node-id=1813%3A74)
- changes `UI.SummaryListItem` paddings
- adds checkboxes to `UI.SummaryListItem`, and that would introduce breaking changes without using "with …
> WMS-802 | Add checkbox support to SummaryListItem

- .github/workflows/ci.yml
- package.json
- tests/Tests/UI/ListView.elm
- yarn.lock
* Adapts CI routine for using newer elm-review flags;
* Separate showcase CI from libs' CI.
* Starting with [node-elm-review 2.5.0](https://github.com/jfmengels/node-elm-review/releases/tag/v2.5.0) we have [flags](https://github.com/jfmengels/node-elm-review/pull/37) for ignoring files and directories;
* This was suggested by jfmengels.
Not tracked.
https://github.com/PaackEng/elm-review-config/pull/5
https://github.com/PaackEng/elm-validate-action/pull/4
> Move to new elm-review's per-project flags

- src/UI/Internal/DialogV2.elm
- src/UI/ListView.elm
Adds support to include a custom dropdown that is toggled by `moreActions` (ellipsis) button.
Required by Fix Issues:
[WMS-803](https://paacklogistics.atlassian.net/browse/WMS-803)
> WMS-803 | ListView's withCustomExtraMenu

- .github/workflows/ci.yml
- .github/workflows/percy.yml
- .percy.yml
- cypress/plugins/index.js
- package.json
- yarn.lock
* Cherry-pick dependencies bumps from dependabot that weren't passing CI;
* Run the migration process as specified in percy's docs.
* The other one was broken;
* The dependencies were outdated.
Not tracked.
> Bump dependencies & migrate to Percy 3.0.0

- src/UI/Icon.elm
- Removes static id from icon.
- Adds "Fixing" icon using an overlay.
[Required for this](https://www.figma.com/file/DTyoSveNksHpZCdU8a7BNs/Dashboard?node-id=2330%3A19005)
[WMS-914](https://paacklogistics.atlassian.net/browse/WMS-914)
Maybe we should change icons API to allow adding this overlay to any icon.
This could be useful if we need more icons like this.
---
**BIG** thanks to @PedroHLC for helping a \***lot**\* with these SVG hacks.
> WMS-914 | Icon for Problem Solving active

- src/UI/ListView/SummaryItem.elm
Adds the following features to `SummaryItem`:
- Entry tone using `withTone`
- Suffix icon using `withIcon`
- Bullet with icon using `withBulletIcon`
Required for problem-solving:
- [The red wrench icon:](https://www.figma.com/file/DTyoSveNksHpZCdU8a7BNs/Dashboard?node-id=2330%3A19005)
- [The background tone and yellow bullet with icon:](https://www.figma.com/file/DTyoSveNksHpZCdU8a7BNs/Dashboard?node-id=1813%3A191)
[WMS-916](https://paacklogistics.atlassian.net/browse/WMS-916)
Spent some extra time trying to properly align that suffix icon, but couldn't without resorting to some ugly hacks including hardcoded sizes. I really think we should ignore that for now and try to align it later...
> WMS-916 | SummaryItem tone, icon and bullet icon

- elm.json
- src/UI/ListView.elm
Fix header width bug that is making the header render one word per line.
The header badge feature introduced along with `3.5.0` changed `Element.width fill` to `Element.width shrink`, this is causing the header to render one word per line. 
This temporary fix should be enough to maintain current styling in pages that aren't using header badges.
> Fix header

- .github/workflows/ci.yml
Removes the experimental elm-bump CI
It was triggering even when no elm files changed.
Not tracked.
Nothing.
It'll be back, I'll elaborate a better script...
> Revert: elm-bump CI

- elm.json
- showcase/src/Radio/Stories.elm
- src/UI/Radio.elm
- Update the Radio component's bullet, font, colors, paddings, etc
- Change the implementation to use `Input.radio` from `elm-ui` for improved accessibility
- Add new `withSize` option 
https://www.figma.com/file/rqAoj2WwQZYoisP2G6d6nJ/Selection-Controls?node-id=348%3A40
[DES-106](https://paacklogistics.atlassian.net/browse/DES-106)
Nothing.
I'm considering creating a `UI.Internal.SelectionControl` on a next PR to put view/logic shared between radio and checkbox. This is another reason why I'm not dealing with error/disabled states in this PR. Error states more specifically should be implemented in the context of other form elements.
> DES-106 | Update radio button

- elm.json
- showcase/src/Main.elm
- showcase/src/Radio/Msg.elm
- showcase/src/Radio/Stories.elm
- src/UI/Checkbox.elm
- src/UI/Effect.elm
- src/UI/Internal/SelectionControl.elm
- src/UI/Internal/Tables/FiltersView.elm
- src/UI/Radio.elm
- Add html ids to the radio buttons
- Update the messaging to send the id when selecting an option
- Update stories to handle the id and focus on the button 
Because the focus was not following the selection
[DES-106](https://paacklogistics.atlassian.net/browse/DES-106)
Nothing.
Not happy at all having to break again the API and also the fact that the burden of focusing on the element lies on who's using it. I'm also not happy having to "generate" an id on the spot, although it should be reliable considering no one should have options with the same label. Any alternatives will be considered, these are some of them:
- Creating a `Radio.update : Radio.Msg -> (RadioState, Effect msg)` and returning a focus effect
- Creating a new entry point of the component as an alternative to …
> Fix radio button

- README.md
- i18n/English.json
- i18n/French.json
- i18n/Spanish.json
- package.json
- showcase/public/index.html
- showcase/src/Layouts/Stories.elm
- showcase/src/Tables/Book.elm
- src/UI/I18n/English.elm
- src/UI/I18n/French.elm
- src/UI/I18n/Spanish.elm
- src/UI/I18n/Types.elm
- src/UI/Internal/Filter/Model.elm
- src/UI/Internal/Filter/Sorter.elm
- src/UI/Internal/Filter/View.elm
- src/UI/Internal/Tables/Filters.elm
- src/UI/Internal/Tables/FiltersView.elm
- src/UI/Internal/Tables/Sorters.elm
- src/UI/Internal/Utils/Element.elm
- src/UI/Radio.elm
- src/UI/Tables/Stateful.elm
- src/UI/Text.elm
- yarn.lock
<div align="center"><img src="https://ae01.alicdn.com/kf/Hf8fe8174b87a4b428e14fc1451f744dea/Filtro-de-caf-em-casa-de-a-o-inoxid-vel-reus-vel-despeje-sobre-dripper-filtro.jpg_Q90.jpg_.webp" width=240 alt="joke" title="reusable filter" /></div>
- Bump paack-ui-assets;
- Add filter component's internals;
- Move table's filter to the component's internal;
- Update style to match Figma;
- Allow sorting with more than alphabetically;
- Add notes about "Fira Sans" weights;
- Fix radio's button text-style.
- First part of what I need in LMO;
- Fresh look.
[DES-111](https://paacklogistics.atlassian.net/browse/DES-111) and [LMO-515](https://paacklogistics.atlassian.net/browse/LMO-515).
Nothing.
In a future PR:
- The API to the Final reusable Filter;
- headerWithFilter / bodyWithFilter;
- Fix of the …
> LMO-515 | DES-111 | Prepare reusable Filter component (Internals)

- showcase/src/Dropdown/Stories.elm
- src/UI/Dropdown.elm
Limits the dropdown part of the Dropdown component to have at most `200px` of height and adds a scrollbar for longer dropdowns.
> also some minor documentation fixes
The current dropdown has no height limit, this can cause issues with or long lists and/or shorter displays.
Change `PaackEng/elm-ui-dropdown` to send `DomFocus` effects when selection change.
> Dropdown scrollbar

- elm.json
- src/UI/Filter.elm
- src/UI/Internal/Filter/View.elm
- src/UI/Internal/Tables/FiltersView.elm
- src/UI/ListView.elm
- Adds support for additional filters in the `ListView`
- This change required adding `withAlignRight` to the `UI.Filter`
- ... and I ended up fixing an unknown issue with the `UI.Filter` button width.
~~the voice inside my head asked it~~
Required for [WS-12](https://paacklogistics.atlassian.net/browse/WS-12)
Depends on usage, but it looks great like this:
```elm
-- showcase/src/Layouts/Stories.elm:127
|> ListView.withFilter
(model.extraFilter
|> Filter.fromModel "Filters"
(LayoutsMsg.ForFilter >> Msg.LayoutsStoriesMsg)
|> Filter.withWidth (Element.minimum 150 Element.fill)
)
```
~~Though I'm not sure why the checkbox is shrinking there...~~ **FIXED**
[WS-12](https://paacklogistics.atlassian.net/browse/WS-12)
Both I and @PedroHLC are very unhappy with how we have to extend the list view …
> Add `Filter` support to `ListView`

- elm.json
- src/UI/ListView.elm
Add support for buttons at the bottom of ListView's action bar.
Some screens in WMS and LMO require this feature (LMO is using a hackish solution for that right now)
Not tracked.
Nothing.
[Figma 1# (WMS)](https://www.figma.com/file/DTyoSveNksHpZCdU8a7BNs/Dashboard?node-id=3469%3A45952)
[Figma 2# (LMO)](https://www.figma.com/file/pPFPQCmjZ9BcuTzqppZbRf/Fleet-Manager-Dashboard?node-id=867%3A57773)
(yeah, I'm too lazy to stretch the button for the screenshot)
> ListView button actions

- elm.json
- showcase/src/TextField.elm
- src/UI/TextField.elm
Show error text below a text field if it applies
Since it was missing
[S4S-110](https://paacklogistics.atlassian.net/browse/S4S-110)
> S4S-110 | Add error text below TextField if it applies

- elm.json
- src/UI/Utils/Focus.elm
Adds blur handler in focus config
Need to show [some suggestion](https://www.figma.com/file/GUqevGHHTKTnZT4VgaXfns/Communications?node-id=900%3A6294) under the `TextField` depending upon the focus status.
Not tracked.
> Adds blur handler in focus config

- elm.json
- src/UI/TextField.elm
Stops making borders red if error caption is an empty string
I had an `error` filed in my model of type `Maybe String`, for `Nothing` values of `error`, I was seeing red borders. Here is a code sample:
```elm
TextField.singlelineText Msg "Label" "value"
|> TextField.withError (error |> Maybe.map identity |> Maybe.withDefault ""
```
https://paacklogistics.atlassian.net/browse/S4S-133
> S4S-133 | If an error caption is empty, it shouldn't make TextField borders red

- elm.json
- src/UI/Dropdown.elm
Allows customizing the followings:
- Width of the dropdown list
- Alignment of the dropdown list
- Prompt text
Because I had to match this [design](https://www.figma.com/file/GUqevGHHTKTnZT4VgaXfns/Communications?node-id=900%3A7945).
[S4S-166](https://paacklogistics.atlassian.net/browse/S4S-166)
> S4S-166 | Add dropdown customizations

- showcase/src/Alerts.elm
- src/UI/Alert.elm
Inline options for displaying alerts
For some use cases, the edge to edge version of the alert doesn't fit nicely in the UI. With this version, we can explore newer placements of the alert component, without covering the entire screen (this is also very useful for showing contextual info sometimes).
Not tracked.
Nothing.
> Add inline alerts

- .github/CODEOWNERS
- elm.json
- package.json
- showcase/src/Main.elm
- showcase/src/Menu/Model.elm
- showcase/src/Menu/Msg.elm
- showcase/src/Menu/Stories.elm
- showcase/src/Model.elm
- showcase/src/Msg.elm
- src/UI/Menu.elm
- yarn.lock
Ports `PopupMenu` from `wms-web` into a more stable `Menu` component.
Many apps are using context menu buttons, this component should fit all these uses.
[WS-544](https://paacklogistics.atlassian.net/browse/WS-544)
[LMO-1407](https://paacklogistics.atlassian.net/browse/LMO-1407)
Nothing.
- Nothing
Screenshots
> WS-544 | LMO-1407 | Add dropdown `Menu` component

- elm.json
- src/UI/Button.elm
- src/UI/Internal/Button.elm
Adds the ability to add an ID to button component
Our squad [need it](https://paacklogistics.atlassian.net/browse/S4S-377) to track clicks on buttons in Timeslot-change page through Google Tag Manager. Here is a small [slack conversation](https://paack.slack.com/archives/CUKQCEN30/p1643367475526139) to have more context.
Not tracked.
> S4S-377 | Add withId for button component

- elm.json
- showcase/src/DatePicker/Stories.elm
- src/UI/DatePicker.elm
- Allow limiting the range of selectable days in the date-picker.
- In LMO, there are use-cases we don't want past dates, and others that we don't want to allow future dates.
[LMO-1615](https://paacklogistics.atlassian.net/browse/LMO-1615).
Nothing.
- @sufiyanyusuf review.
> LMO-1615 | Allow disable future/past days in the date-picker

- elm.json
- showcase/src/Tables/Stories.elm
- src/UI/Internal/Tables/Paginator.elm
- src/UI/Tables/Stateful.elm
- Adds `withHeight` to the stateful table.
- Adds a a scrollbar to the stateful tables that have a paginator.
Fixes a design issue on wms.
It unblocks first pending point on https://github.com/PaackEng/wms-web/pull/630
I don't think solving the second point is worth for now.
[WS-564](https://paacklogistics.atlassian.net/browse/WS-564)
Nothing.
Nothing.
Already up and running on https://paackeng.github.io/paack-ui/#Complex%20components/Tables/Desktop
> WS-564 | Paginator scroll

- src/UI/Internal/Tables/Paginator.elm
- src/UI/Menu.elm
WS-659 | Allow changing the direction UI.Menu opens to.
You can't change the amount of entries in a fullscreen table.
[WS-659](https://paacklogistics.atlassian.net/browse/WS-659)
Nothing.
Nothing.
> WS-659 | Allow changing the direction UI.Menu opens

- elm.json
- src/UI/Internal/Tables/Paginator.elm
FIxes another issue in the page number calculation, this time found by me on staging.
The last fix was enough to fix the bug reported by Razvan, but it still had another issue.
In this version, I took more care and tested every situation that the paginator would have to deal with, and it's calculating correctly in every case.
Not tracked.
Nothing.
- Nothing.
Nothing.
> Fix paginator range and total calculation

- elm.json
- package.json
- src/UI/Document.elm
- Allow injecting extra HTML tags in the page's body.
- Needed for JS integrations.
Helps me in [LMO-2043](https://paacklogistics.atlassian.net/browse/LMO-2043).
Nothing.
Nothing.
> LMO-2043 | Extra HTML
