PaackEng/paack-ui

.github/workflows/ci.yml
This GitHub action does:
1 - Validate format with `elm-format`
2 - Compile documentation code
3 - Run tests
=> WMS-132 | Add CI workflow

src/UI/Internal/Primitives.elm, src/UI/Internal/Text.elm, src/UI/TextField.elm
* Expose Text's attributes and default color
* Use Text for styling TextField's label
* Fix fields' border rounding
* Make text bold in mobile
=> WMS-142 | Fixes UI inconsistency for login screen

elm.json, src/UI/Icon.elm, src/UI/Internal/Menu.elm, src/UI/Internal/SideBar.elm, src/UI/NavigationContainer.elm, src/UI/Palette.elm, src/UI/Utils/Element.elm
Objective:
* Follow [Sufiyan’s design pattern](https://www.sketch.com/s/a252928f-582c-4f38-a5ee-14d60a2a3067/a/zaaeQy) guidelines
* Follow Elm’s with-pattern API guidelines
* Develop one component capable to adapt as:
=> WMS-150 | Add NavigationContainer

docs/src/Icons.elm, docs/src/Palette.elm, docs/src/Texts.elm, src/UI/Alert.elm, src/UI/Badge.elm, src/UI/Button.elm, src/UI/Internal/Dialog.elm, src/UI/Internal/Palette.elm, src/UI/Internal/SideBar.elm, src/UI/Internal/Text.elm, src/UI/NavigationContainer.elm, src/UI/Palette.elm, src/UI/SelectList.elm, src/UI/Text.elm, src/UI/TextField.elm, src/UI/Utils/Element.elm
This takes care of two things that were annoying me:
* Paragraphs were blindly used (they still are misused, but we can fix them now)
* Text was hacking colors palette, now the only one doing it is the light button when it's disable.
This took me more time then I wished for, sorry...
=> Text API v2

src/UI/Alert.elm, src/UI/Badge.elm, src/UI/Button.elm, src/UI/Icon.elm, src/UI/Internal/Dialog.elm, src/UI/Internal/SideBar.elm, src/UI/Internal/Text.elm, src/UI/NavigationContainer.elm, src/UI/SelectList.elm, src/UI/Table.elm, src/UI/Text.elm, src/UI/TextField.elm, src/UI/Utils/Element.elm, tests/Tests/UI/TextField.elm
New features:
* New icons
* Badge can have custom brightness
* Buttons can have message mapped
* Alert now has a "light" (gray.lighter) tone
* Dialogs can define a maximum width on its container
* Dialogs are now responsive
* ContentStackChild now has buttons!
Fixes:
* Table width was not being applied
* TextField's label rendering code was totally wrong
* Button.ButtonBody doesn't need that "msg" anymore
* Button.BodyIco renders square
* SelectList search's field doesn't have visible label
=> WMS-143 | Add Spaces screen (pt 3A)

docs/src/Main.elm, docs/src/Model.elm, docs/src/Msg.elm, docs/src/Paginators/Model.elm, docs/src/Paginators/Msg.elm, docs/src/Paginators/Stories.elm, src/UI/Icon.elm, src/UI/Paginator.elm, src/UI/Utils/Element.elm
=> WMS-197 | Implement Paginator component

src/UI/Icon.elm, src/UI/Internal/Text.elm, src/UI/SelectList.elm, tests/Tests/Utils/Element.elm
* [Icon] Add withColor (don't break API with ColorInherit by default);
* [Icon] Add toggle-up/down icons;
* [SelectList] Remove padding so it can be managed from View;
* [Text] Add line-height to overline (for multiline/combinations)
=> WMS-145 | Package screen required changes

src/UI/Paginator.elm
My bad 💩 (this also explicitly says the lack of tests here, I will add the tests as soon as possible)
=> Fix pagination when total count is less than a page

src/UI/Internal/Text.elm, src/UI/Text.elm
A non-breaking, easier to comprehend version of 71be1ad
=> Allow ellipsis to apply in more than just a simple one-line text.

src/UI/NavigationContainer.elm, src/UI/RenderConfig.elm
* Only consider width for device's class;
* Don't destroy any html element when opening/closing dialogs.
=> Fix Juan's bugs

.github/workflows/ci.yml, elm-analyse.json, elm.json, package.json, src/UI/ActionBar.elm, src/UI/Badge.elm, src/UI/Button.elm, src/UI/Icon.elm, src/UI/Internal/Dialog.elm, src/UI/Internal/Menu.elm, src/UI/Internal/SideBar.elm, src/UI/Internal/Text.elm, src/UI/Link.elm, src/UI/NavigationContainer.elm, src/UI/SelectList.elm, src/UI/Table.elm, src/UI/Text.elm, src/UI/TextField.elm, src/UI/Utils/Element.elm, yarn.lock
A list of checks are available in:
https://stil4m.github.io/elm-analyse/#/messages
Feel free to start a discussion about the included/disabled checks in `elm-analyse.json`
=> WMS-138 | Setup elm-analyse

src/UI/Button.elm
=> WMS-307 | Button's elm-compatible documentation

showcase/src/Icons.elm, src/UI/Icon.elm, src/UI/Internal/SideBar.elm, src/UI/Paginator.elm
<center style="text-align:center"><img src=https://media.giphy.com/media/3oxRmoTueKDmUguzL2/giphy.gif alt="Feeling like a wizard" /></center>
=> WMS-307 | Icon's elm-compatible documentation

showcase/src/Icons.elm, src/UI/Icon.elm, src/UI/Internal/FiltersHeaders.elm
Surprise, Suprise, the icon was already there :D
=> Add filter icon function

package.json, showcase/src/Checkboxes/Model.elm, showcase/src/Checkboxes/Msg.elm, showcase/src/Checkboxes/Stories.elm, showcase/src/Main.elm, showcase/src/Model.elm, showcase/src/Msg.elm, showcase/src/Radio/Model.elm, showcase/src/Radio/Msg.elm, showcase/src/Radio/Stories.elm, showcase/src/Tables/Stories.elm, src/UI/Checkbox.elm, src/UI/Icon.elm, src/UI/Internal/DateInput.elm, src/UI/Internal/Filters.elm, src/UI/Internal/FiltersHeaders.elm, src/UI/Internal/TableView.elm, src/UI/Radio.elm, src/UI/RadioButton.elm, src/UI/Tables/Stateful.elm, src/UI/Utils/ARIA.elm, yarn.lock
[ Requires #51 ]
Also fixes an alignment thing on Table, and put hover style on filter header. (sorry)
=> WMS-315 | Update Checkbox and RadioButton to match Figma

showcase/src/LoadingView.elm, showcase/src/Utils.elm, src/UI/Checkbox.elm, src/UI/Internal/Dialog.elm, src/UI/Internal/FiltersHeaders.elm, src/UI/Internal/Tables/Common.elm, src/UI/Internal/Tables/Filters.elm, src/UI/Internal/Tables/FiltersView.elm, src/UI/Internal/Tables/View.elm, src/UI/Radio.elm, src/UI/Tables/Common.elm, src/UI/Tables/Stateful.elm, src/UI/Tables/Stateless.elm
Summary is the names of the commits.
=> Figma Sync

showcase/src/Buttons/Stories.elm, src/UI/Button.elm
=> WMS-404 | Fix ToggleButton theme

showcase/src/Sizes.elm, src/UI/Internal/Palette.elm, src/UI/Palette.elm
I also renamed an internal function, I think makes more sense right now, but if not, gimme so suggestions :D
=> WMS-402 | Fix contrast color to alert and badges in warning mode

.github/workflows/PULL_REQUEST_TEMPLATE.md
Adding a PR template, the template is:
Describe here
Describe here
[JIRA-CODE](jira-url)
[JIRA-CODE](jira-url) or [PR#CODE](pr-url)
This is optional, but you can add any other useful information that would not fit in the other topics.
=> Add PR template

showcase/src/Badges.elm, src/UI/Badge.elm, tests/Tests/UI/Badge.elm
Replaces colors and API to fit Figma cases.
Sufyian changed it.
[WMS-412](https://paacklogistics.atlassian.net/browse/WMS-412)
The Pull Request didn't pop up with the template.
=> WMS-412 | Sync Badges' colors with Figma

showcase/src/Checkboxes/Stories.elm, showcase/src/Tables/Book.elm, showcase/src/Tables/Model.elm, showcase/src/Tables/Msg.elm, showcase/src/Tables/Stories.elm, src/UI/Badge.elm, src/UI/Checkbox.elm, src/UI/Internal/Tables/FiltersView.elm, src/UI/Internal/Tables/View.elm, src/UI/Tables/Stateful.elm, src/UI/Tables/Stateless.elm, src/UI/Utils/ARIA.elm
Add a checklist on each row.
As a WH Manager and Supervisor, I want to create a group of packages selecting packages one per one.
[WMS-440](https://paacklogistics.atlassian.net/browse/WMS-440)
I use a xor mask for doing the toggle-all button in O(1). Gladly this is the fastest operation known in computer science. Fast in RISC, CISC, SIMD, and JavaScript VMs.
=> WMS-440 | Adapt Table componet to allow selecting multiple rows

elm.json, showcase/src/Main.elm, showcase/src/Model.elm, showcase/src/Msg.elm, showcase/src/Tabs/Model.elm, showcase/src/Tabs/Msg.elm, showcase/src/Tabs/Stories.elm, src/UI/Tables/Common.elm, src/UI/Tabs.elm, src/UI/Utils/ARIA.elm, tests/Tests/UI/Tabs.elm
Add a new component: Tabs
It's used in WMS Phase3 Group's screen.
[WMS-441](https://paacklogistics.atlassian.net/browse/WMS-441)
--
=> WMS-441 | Add Tabs component

cypress/integration/visual-regression.spec.js, yarn.lock
* Bump node-elm-compiler
* Add Tabs to cypress
1 - Keeping project updated
2 - I forgot
None
None
None
None
=> Bump node-elm-compiler; Add Tabs to cypress

cypress/integration/visual-regression.spec.js
Adds missing stories to Percy
Because they were missing
[WMS-474](https://paacklogistics.atlassian.net/browse/WMS-474)
=> WMS-474 | Add missing stories to Percy

elm.json, package.json, showcase/src/Alerts.elm, showcase/src/Badges.elm, showcase/src/Buttons/Stories.elm, showcase/src/Checkboxes/Stories.elm, showcase/src/Icons.elm, showcase/src/LoadingView.elm, showcase/src/Main.elm, showcase/src/Paginators/Stories.elm, showcase/src/Palette.elm, showcase/src/Radio/Stories.elm, showcase/src/Sizes.elm, showcase/src/Tables/Book.elm, showcase/src/Tables/Stories.elm, showcase/src/Tabs/Model.elm, showcase/src/Tabs/Stories.elm, showcase/src/TextField.elm, showcase/src/Texts.elm, showcase/src/Utils.elm
Add showcase to the "source-directories" and ran elm-analyse on it.
Cause that code was a reason for shame.
[WMS-462](https://paacklogistics.atlassian.net/browse/WMS-462
None.
- Tests, but will be done in a separate PR.
=> WMS-462 | Cleanup/Analyse Showcase

src/UI/ListView.elm, src/UI/Utils/Element.elm, tests/Tests/UI/ListView.elm
* Remove `border-right` from ListView
* Remove `RenderConfig` from ListView's Lambdas
Required to reuse ListViews better-
[WMS-484](https://paacklogistics.atlassian.net/browse/WMS-484 and partially [WMS-500](https://paacklogistics.atlassian.net/browse/WMS-500
None
=> WMS-500 | WMS-484 | Part one of changes required to Group Views

elm.json, tests/Tests/UI/Alert.elm, tests/Tests/UI/Badge.elm, tests/Tests/UI/Button.elm, tests/Tests/UI/ListView.elm, tests/Tests/UI/Tabs.elm, tests/Tests/UI/TextField.elm, tests/Tests/Utils/ExtraSelectors.elm
Finish this task (finally)!
Do the proper cleanup after running elm-analyse.
Cause we like elegant code!
And some times I need a light-mind task...
[WMS-462](https://paacklogistics.atlassian.net/browse/WMS-462)
None, based on master.
=> WMS-462 | Use analyse in tests & showcase (Part 2)

cypress/integration/visual-regression.spec.js, showcase/src/Alerts.elm, showcase/src/Badges.elm, showcase/src/Buttons/Stories.elm, showcase/src/Sizes.elm, showcase/src/TextField.elm, src/UI/Checkbox.elm
@renanpvaz  already removed Chrome and Mobile screenshots in Percy. This PR completes this by grouping components variations on one page.
* I decided to keep tables separated as they are more complex and way larger.
Cause we were breaking the free quotes.
[WMS-535](https://paacklogistics.atlassian.net/browse/WMS-535)
Nothing.
Feel free to discuss the table decision.
=> WMS-535 | Percy Improvements

src/UI/Checkbox.elm, src/UI/Internal/Dialog.elm
* Does not allow checkbox event to be supressed
* Wrap dialog's title (to match the dialog's body width)
Changes required for WMS' Phase 3
Not tracked.
Nothing
=> WMS-Phase3 | Some fixes

src/UI/Badge.elm, src/UI/SummaryListItem.elm
* Do not wrap Badges
* Keep badge color when not selected
Needed in WMS' phase 3
Not tracked.
Not blocked, basted on the master branch.
Nothing.
=> WMS-Phase3 | Badges fixes

.github/workflows/ci.yml
Apply the fix from https://github.com/PaackEng/wms-web/pull/147
=> Add step to fix elm cache

.github/workflows/ci.yml, .percy.yml
Adding the percy config file to avoid taking 375px snapshots
=> Add percy's missing config

src/UI/Badge.elm, src/UI/Internal/Basics.elm, src/UI/Internal/Dialog.elm, src/UI/ListView.elm
* Add border-radius to dialog
* Add missing docs to Badge
* Add ListView.withSelectStyle 
Missing WMS' Phase 3 features.
Not tracked.
=> Border-radius to Dialog; add ListVIew.withSelectStyle

.editorconfig, package.json
Add the editor config as agreed on https://github.com/PaackEng/wms-web/pull/146
=> Add editorconfig and prettier

src/UI/TextField.elm, src/UI/Utils/Element.elm
The same as #107 but applying to password.
The last PR added LastPass to the username field, but they didn't sync when auto-filling.
https://paacklogistics.atlassian.net/browse/WMS-589
Not blocked.
Nothing.
I previously misjudged this as unnecessary, sorry for the double reviewing...
=> WMS-589 | Make our login page comply to LastPass (apply to password too)

cypress/integration/visual-regression.spec.js, showcase/src/Radio/Msg.elm, showcase/src/Radio/Stories.elm, src/UI/Radio.elm
Add an option for horizontally laid radio buttons
Need them before we can merge [this PR](https://github.com/PaackEng/wms-web/pull/174)
[WMS-605](https://paacklogistics.atlassian.net/browse/WMS-605)
=> WMS-605 | Add an option for horizontally laid radio buttons

showcase/src/Layouts/Stories.elm, showcase/src/Tables/Book.elm, src/UI/Internal/Tables/View.elm, src/UI/Internal/ToggleableList.elm, src/UI/ListView.elm, src/UI/Tables/Common.elm, src/UI/Tables/Stateful.elm, tests/Tests/UI/ListView.elm
Uses `Element.Keyed` in `UI.Table`.
To enhance diffing, and maybe speed up with less "redraws".
Not tracked.
#90
=> Use Keyed in ListView

elm.json, showcase/elm.json, tests/Tests/UI/Tabs.elm, tests/Tests/UI/TextField.elm, tests/Tests/Utils/ExtraEvents.elm
Bump some dependencies and recreate the "indirect" dependencies list!
So we can deploy again...
Not tracked.
Nothing
=> Bump dependencies

src/UI/Internal/Tables/Common.elm, src/UI/Internal/Tables/View.elm, src/UI/Tables/Common.elm
* Move `cellLink` to UI.Table
* This code was in the app and may be reused.
[WMS-676](https://paacklogistics.atlassian.net/browse/WMS-676)
Not blocked.
Nothing.
=> WMS-676 | Move cellLink to UI.Table

showcase/src/Icons.elm, src/UI/Icon.elm
Two missing icons
Because I need them and they were in the assets already
[BRMS-37](https://paacklogistics.atlassian.net/browse/BRMS-37)
=> BRMS-37 | Add move and trash icons

src/UI/Utils/TypeNumbers.elm
Add the possibility to create tables with more than nine columns.
* Because the sky isn't the limit;
* The WMS' Package Table now has twelve columns.
Not tracked.
Not blocked.
Nothing.
=> Add decimal to UI.Utils.TypeNumbers

.github/workflows/percy.yml, cypress.json, package.json, yarn.lock
* Bumps percy to "2.3.2"
* Bumps  cypress to "5.6.0"
* Was trying to solve the problem with tootlip's texts.
Not tracked.
Not blocked.
Nothing.
=> Bumps Percy

i18n/French.json, src/I18n/French.elm, src/UI/Internal/RenderConfig.elm, src/UI/RenderConfig.elm
Adding french translations to paack-ui
Because WMS needs it
[WMS-730](https://paacklogistics.atlassian.net/browse/WMS-730)
This is blocked by the correct translations.
=> WMS-730 | Add french language boilerplate

.github/workflows/ci.yml, src/UI/Radio.elm, src/UI/Utils/Action.elm
* Remove no longer required fix in CI
* Add Docs to CI
* Fix all docs realted problems...
* Because PRs are being pushed breaking docs.
[WMS-728](trust-me)
Not blocked.
=> WMS-728 | Docs in CI

showcase/src/Palette.elm, showcase/src/Sizes.elm, src/UI/Badge.elm, src/UI/Button.elm, src/UI/Checkbox.elm, src/UI/Internal/Colors.elm, src/UI/Internal/Dialog.elm, src/UI/Internal/Nav/StackHeader.elm, src/UI/Internal/SideBar.elm, src/UI/Internal/Tables/FiltersView.elm, src/UI/Internal/Tables/View.elm, src/UI/Internal/Text.elm, src/UI/Internal/Utils/Element.elm, src/UI/ListView.elm, src/UI/Palette.elm, src/UI/Radio.elm, src/UI/Tabs.elm, src/UI/TextField.elm
Add one shorthand per color variant.
Also had to fix ambiguous imports
To reduce verbosity when using colors
=> RFC-005 | Palette color shorthand

src/UI/Internal/Utils/Element.elm, src/UI/ListView.elm
* Add id to elements in ListView when  `ListView.withDomIds "somePrefix"` is used
* Required for https://github.com/PaackEng/wms-web/pull/242
Not tracked.
Not blocked.
Nothing
=> Allow scrolling to element in list

package.json, src/UI/Layout/SplitSelectable.elm, src/UI/V2/Dialog.elm, yarn.lock
Fix some broken links and bad formatting in docs. Also includes server to preview the docs.
Because links were broken
=> Fix broken docs

cypress/integration/visual-regression.spec.js, showcase/src/Dialog.elm, src/UI/Internal/DialogV2.elm, src/UI/V2/Dialog.elm
Adds mobile view for dialog component
Since it was missing and [mocks](https://www.figma.com/file/Jra5ja8zLZXxkYTk6gFZsq/Modals?node-id=163%3A53) were not present because Sufyan was on holidays.
[WMS-715](https://paacklogistics.atlassian.net/browse/WMS-715)
=> WMS-715 | Mobile view for V2 of Dialog component

yarn.lock
* Upgrade all dependencies' dependencies
* Including cypress' axios (through https://github.com/percy/percy-agent/releases/tag/v0.28.6)
Solves https://npmjs.com/advisories/1594
Not tracked.
Not blocked.
Nothing.
=> Upgrades dependencies' dependencies

.github/CODEOWNERS
=> Add Christian as codeowner

elm.json
=> Release 2.0.0

showcase/src/Layouts/Stories.elm, showcase/src/Tables/Stories.elm
* Add minimal height to height=fill components
* They were not showing in showcase...
Not tracked.
Not blocked.
=> [Showcase] Add minimal height to height=fill components

cypress/integration/visual-regression.spec.js, showcase/src/Main.elm, showcase/src/Model.elm, showcase/src/Msg.elm, showcase/src/Sidebar/Model.elm, showcase/src/Sidebar/Msg.elm, showcase/src/Sidebar/Stories.elm, showcase/src/Utils.elm, src/UI/Internal/Colors.elm, src/UI/Internal/SideBar.elm, src/UI/Internal/Utils/Element.elm, src/UI/NavigationContainer.elm, src/UI/Utils/Element.elm
- Add a new story with the sidebar variants
- Update the current sidebar to match the design
- Refactor conflicting spacing and other styles in the sidebar
- Include the non-persistent variant of the sidebar
- Add option to enable the non-persistent sidebar to the navigation container    
**Note**: this one is a doozy but please review extra carefully [here](https://github.com/PaackEng/paack-ui/pull/157/files#diff-be613155231ad86ba193a845a2521baa31c13abca43a6e5a8ace02d417ae43c1) 
Because the non-persistent sidebar variant is going to be used in BRMS and the standard sidebar was updated so that both look the same.
[DES-22](https://paacklogistics.atlassian.net/browse/DES-22)
=> DES-22 | update sidebar

elm.json, package.json, showcase/src/Sidebar/Stories.elm, src/UI/NavigationContainer.elm, src/UI/Utils/Element.elm, yarn.lock
Update paack-ui-assets
Bump major
Because a new version was published tweaking some icons
=> Bump and update paack-ui-assets

elm.json, src/UI/Internal/Menu.elm, src/UI/NavigationContainer.elm
Add an actual new entry point for the nav state instead of hacking my way around it
Because my past "fix" forces the menu to never open :facepalm:  
Sorry, this time it'll work
=> HOTFIX (again?) | Add entry point for nav state with the menu closed

src/UI/Internal/Colors.elm
Replace lightest red tone.
To sync with Figma color palette.
[DES-67](https://paacklogistics.atlassian.net/browse/DES-67)
=> DES-67 | Update colors

elm.json
UI.ContentPlaceholder
Added:
configure : String.String -> UI.Icon.Icon
fix : String.String -> UI.Icon.Icon
=> elm-bump: 3.1.0

i18n/English.json, i18n/French.json, i18n/Spanish.json, showcase/src/Layouts/Model.elm, showcase/src/Layouts/Msg.elm, showcase/src/Layouts/Stories.elm, src/I18n/English.elm, src/I18n/French.elm, src/I18n/Spanish.elm, src/I18n/Types.elm, src/UI/Icon.elm, src/UI/ListView.elm, tests/Tests/UI/ListView.elm
Update ListView to be more consistent with [figma](https://www.figma.com/file/DTyoSveNksHpZCdU8a7BNs/Dashboard?node-id=104%3A1804):
It's part of the problem-solving flow.
[WMS-800](https://paacklogistics.atlassian.net/browse/WMS-800)
- I'll Include the input icon in the next PR.
=> WMS-800 | Update ListView style

src/UI/Icon.elm
Adds bolt icon
Used several times in Fix Issues pages.
=> Add Fix Issues icon

elm.json, src/UI/Icon.elm
Bumps package version to 3.2.0
Fix Issues page requires some new features included in this version.
=> Bump to 3.2.0

showcase/src/Sizes.elm, src/UI/Internal/Colors.elm, src/UI/Internal/Nav/StackHeader.elm, src/UI/Internal/SideBar.elm, src/UI/Internal/Tables/FiltersView.elm, src/UI/Internal/Tables/View.elm, src/UI/ListView.elm, src/UI/Palette.elm, src/UI/Radio.elm, src/UI/Switch.elm, src/UI/Tabs.elm, src/UI/TextField.elm
Update colour palettes.
Breaks the way we refer to light and dark shades internally because we have "lighter than lightest" shades being used around.
[Problem-solving requires the fourth light shade of yellow](https://www.figma.com/file/T885YF0d8G5yWuI9EC49rc/Colors?node-id=0%3A1)
Maybe revert the `darkest` changes.
=> Update colour palettes

elm.json
Bumps version to 3.3.0.
To publish changes required by the problem-solving flow.
=> Bump to 3.3.0

elm.json, showcase/src/Sidebar/Stories.elm, src/UI/Internal/SideBar.elm, src/UI/NavigationContainer.elm
* Hides the vertical bar with the toggle/sandwich button with non-persistent sidebar;
* Exposes the message of showing/hiding the menu using functions.
* I'll have to put the sandwich button in a special complex component.
[LMO-438](https://paacklogistics.atlassian.net/browse/LMO-438)
=> LMO-438 | Allow manually placing the menu button for non-persistent sidebar

.github/CODEOWNERS, .github/PULL_REQUEST_TEMPLATE.md
* Drop Jou
* Add Nicola
* Prettify PULL_REQUEST_TEMPLATE
=> Update CODEOWNERS & prettify PULL_REQUEST_TEMPLATE

showcase/src/Layouts/Model.elm, showcase/src/Layouts/Msg.elm, showcase/src/Layouts/Stories.elm, src/UI/ListView.elm
* Add `UI.ListView.withBadgedHeader`
To match [this design](https://www.figma.com/file/pPFPQCmjZ9BcuTzqppZbRf/Fleet-Manager-Dashboard?node-id=533%3A225)
[LMO-460](https://paacklogistics.atlassian.net/browse/LMO-460).
Nothing.
Testing
=> LMO-460 | Add badges to ListView's header

elm.json, i18n/English.json, i18n/French.json, i18n/Spanish.json, src/UI/I18n/English.elm, src/UI/I18n/French.elm, src/UI/I18n/Spanish.elm, src/UI/I18n/Types.elm, src/UI/ListView.elm
- Adds a button to select every entry from a `ListView`
- Bumps version to 3.5.0.
[Figma](https://www.figma.com/file/DTyoSveNksHpZCdU8a7BNs/Dashboard?node-id=2449%3A27203)
[DES-104](https://paacklogistics.atlassian.net/browse/DES-104)
Ignore the outdated typography styles, we should be updated it in another PR.
=> DES-104 | Add "select all" button to ListView

elm.json, showcase/public/docs.css, showcase/public/index.html, showcase/src/Texts.elm, src/UI/Internal/Text.elm, src/UI/RenderConfig.elm
- Replace font with Fira Sans
- Update font sizes, line heights and letter spacing
- Update showcase to look more like Figma 
https://www.figma.com/file/oJRe2H8jpKobAJ8Fup6dCl/Typography?node-id=453%3A132
[DES-97](https://paacklogistics.atlassian.net/browse/DES-97)
Nothing.
This is optional, but you can add any other useful information that would not fit in the other topics.
=> DES-97 | Typography updates

.github/workflows/ci.yml, elm.json, src/UI/ListView.elm
* Bump version;
* Add CI to stop forgetting to bump version.
* Guess it!
Not tracked.
Nothing.
=> Add CI to stop forgetting about bumping version

cypress/integration/visual-regression.spec.js, elm.json, i18n/English.json, i18n/French.json, i18n/Spanish.json, showcase/elm.json, showcase/src/Dropdown/Model.elm, showcase/src/Dropdown/Msg.elm, showcase/src/Dropdown/Stories.elm, showcase/src/Main.elm, showcase/src/Model.elm, showcase/src/Msg.elm, src/UI/Dropdown.elm, src/UI/Effect.elm, src/UI/I18n/English.elm, src/UI/I18n/French.elm, src/UI/I18n/Spanish.elm, src/UI/I18n/Types.elm
Adds dropdown component.
- Basic dropdown
- Filterable dropdown
[Figma:](https://www.figma.com/file/DTyoSveNksHpZCdU8a7BNs/Dashboard?node-id=2666%3A44774)
[DES-100](https://paacklogistics.atlassian.net/browse/DES-100)
Some colors aren't 1:1, but they aren't present in the palette.
Maybe I should hardcode them for now 🤔 
Also, I could not get the font weights right for a screenshot
I spent quite some time on this, but still, I'm not happy with the outcome.
The main problem is with the update requiring `RenderConfig` and `Dropdown item msg`, we should refactor `elm-ui-dropdown` to fix that.
Another thing, the major bump to `4.0.0` is there because there's a breaking change in `UI.Effect` (a new `DomFocus` effect).
=> DES-100 | Dropdown

src/UI/Dropdown.elm
Fix dropdown module docs.
Forgot to add filterable here 🙃
=> Fix dropdown module docs

elm.json, src/UI/Button.elm, src/UI/Utils/ARIA.elm
- Add `title` attribute to icon buttons (this is temporary, the goal is to use tooltips later)
- Fix the ARIA attributes of buttons
To improve accessibility 
Not tracked.
Nothing.
This is optional, but you can add any other useful information that would not fit in the other topics.
=> Improve accessibility of buttons

package.json, showcase/src/Sizes.elm, src/UI/Checkbox.elm, src/UI/Internal/Colors.elm, src/UI/Internal/Nav/StackHeader.elm, src/UI/Internal/SelectionControl.elm, src/UI/Internal/SideBar.elm, src/UI/Internal/Tables/FiltersView.elm, src/UI/Internal/Tables/View.elm, src/UI/ListView.elm, src/UI/Palette.elm, src/UI/Switch.elm, src/UI/Tabs.elm, src/UI/TextField.elm
* Add the new colors to the INTERNAL module;
* Update internal references;
* Backports colors to the old API.
* I was needing it to the new Filters.
[DES-CODE](https://paacklogistics.atlassian.net/browse/DES-120).
Nothing.
@renanpvaz to do the new API, with all the shades...
=> DES-120 | New colors (without new API)

src/UI/NavigationContainer.elm
* Add `UI.Nav.stateUpdateWithoutPerform`
- So we can get rid of hacks in WMS, LMO and REMS.
Not tracked.
Nothing.
=> Effects | Add UI.Nav.stateUpdateWithoutPerform

elm.json, package.json, showcase/src/Buttons/Stories.elm, showcase/src/Sizes.elm, src/UI/Button.elm, src/UI/Internal/Button.elm, yarn.lock
- Add `Button.fromLabeledOnLeftIcon` and `Button.fromLabeledOnRightIcon`;
- Add previews to showcase;
- Bump dependencies.
- Figma consistency.
[DES-121](https://paacklogistics.atlassian.net/browse/DES-121).
Nothing.
- This is just the pointed feature, the entire button design still needs to be revisited since UX team redesigned it.
=> DES-121 | Add labeled icons to buttons

elm.json, i18n.json, i18n/English.json, i18n/French.json, i18n/Spanish.json, src/UI/I18n/English.elm, src/UI/I18n/French.elm, src/UI/I18n/Spanish.elm, src/UI/I18n/Types.elm
- Bump translations;
- Bump PATCH version;
- Prettify `.i18n.json`
- It was outdated;
- New `"emptyFallback"` feature was added in #289 (merged in #294)
Not tracked.
Nothing.
Nothing.
=> Bump translations

elm.json, showcase/src/Alerts.elm, showcase/src/Icons.elm, src/UI/Alert.elm, src/UI/Icon.elm, src/UI/Internal/Svg.elm, src/UI/LoadingView.elm
- Add generic icons to Alerts;
- Simplify `UI.Icon` by removing giant enum;
- Add `UI.Icon.loader` and `reload`;
- Make `UI.Icon.loader` spin;
- Fix alert's height (40px and not 39px).
- Needed to sync LMO with Figma.
Not tracked.
#295 
- Nothing.
=> Alerts and icons.

package.json, src/UI/Button.elm, src/UI/Internal/Button.elm, yarn.lock
Buttons related:
- Adjust colors;
- Adjust icon's size;
- Adjust padding when using "label + icon" body.
Once again, revisit buttons to get them closer to new Figma specs.
[LMO-862](https://paacklogistics.atlassian.net/browse/LMO-862).
Nothing.
In another PR:
- Focus state / Keyboard navigation;
- "On" state.
=> LMO-862 | Finish polishing button with label and icon.

README.md, elm.json, src/UI/Document.elm
- Publish missing `UI.Document.modelUpdateWithoutPerform`;
- Update README;
- Bump version.
:hand_over_mouth: 
Not tracked.
Nothing.
My apologies.
=> UI.Document.modelUpdateWithoutPerform

elm.json, showcase/src/Icons.elm, src/UI/Icon.elm
Adds missing icon
Need it [here](https://www.figma.com/file/GUqevGHHTKTnZT4VgaXfns/Communications?node-id=900%3A8505)
[S4S-155](https://paacklogistics.atlassian.net/browse/S4S-155)
=> S4S-155 | Adds a missing icon

package.json, showcase/src/Icons.elm, src/UI/Icon.elm, yarn.lock
Add `UI.Icons.unassignPerson`
Missing from here.
[LMO-1030](https://paacklogistics.atlassian.net/browse/LMO-1030).
Nothing.
Nothing.
=> LMO-1030 | Add UI.Icons.unassignPerson

elm.json, src/UI/Icon.elm
- Returns the loader icon to spinning format.
- I accidentally removed it;
Not tracked.
Nothing.
=> Fix loader spinning animation

elm.json, showcase/src/Tables/Stories.elm, src/UI/Tables/Stateful.elm
Fix a remaining issue with the table width configuration.
Making things ugly on wms.
Not tracked.
Nothing.
Nothing.
=> Fix issue with stateful table width

elm.json
Describe here
Describe here
[DES-CODE](https://paacklogistics.atlassian.net/browse/DES-CODE) or Not tracked.
[JIRA-CODE](https://paacklogistics.atlassian.net/browse/JIRA-CODE) or [PR#CODE](pr-url) or Nothing.
This is optional, but you can add any other useful information that would not fit in the other topics.
=> Fix version bump

elm.json, src/UI/Internal/Tables/Paginator.elm
FIxes an issue in the page number calculation found by Razvan on staging.
Well, it fixes a bug.
Not tracked.
Nothing.
- Nothing.
Nothing.
=> Fix paginator page nums

.github/workflows/ci.yml, elm.json, package.json, showcase/src/Main.elm, showcase/src/Menu/Stories.elm, src/UI/Checkbox.elm, src/UI/Internal/Clickable.elm, src/UI/Internal/DateInput.elm, src/UI/Internal/Filter/Update.elm, src/UI/Internal/Filter/View.elm, src/UI/Internal/LegacySideBar.elm, src/UI/Internal/Page.elm, src/UI/Internal/SideBar.elm, src/UI/Internal/Tables/Paginator.elm, src/UI/Internal/Text.elm, src/UI/Internal/Utils/Element.elm, src/UI/Menu.elm, src/UI/Switch.elm, src/UI/Tables/Stateful.elm, src/UI/Text.elm, tests/Tests/Utils/Element.elm, tests/Tests/Utils/ExtraSelectors.elm, yarn.lock
- Update to https://github.com/PaackEng/elm-review-config/pull/9
- New optimization to our codebase.
Not tracked.
- https://github.com/PaackEng/elm-review-config/pull/9
- Elm teammates' approval;
- A bump in https://github.com/PaackEng/elm-validate-action
=> Apply new review rules (1.2.0)

elm.json, package.json, src/UI/Icon.elm, yarn.lock
- Add two new icons: `arrowShapeUp` and `circle`.
I need `arrowShapeUp` for LMO-1789
[LMO-1789](https://paacklogistics.atlassian.net/browse/LMO-1789).
Nothing.
Nothing.
=> LMO-1789 | Sync Icons

elm.json, package.json, src/UI/Icon.elm
- Fix the Walk icon.
- It wasn't showing up.
Not tracked.
Nothing.
Nothing.
Nothing.
=> Fix Walk icon
